# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180323_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.UserGroup', verbose_name='用户组'),
        ),
    ]
