# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180323_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_group', to='accounts.UserGroup', verbose_name='用户组'),
        ),
    ]
