# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180323_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=128, null=True, upload_to='user_images/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
