# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180303_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', max_length=128, upload_to='user_images/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
