# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180326_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': (('get_user', '查看用户'), ('add_user', '添加用户'), ('edit_user', '编辑用户'), ('del_user', '删除用户')), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'default_permissions': (), 'permissions': (('get_usergroup', '查看用户组'), ('add_usergroup', '添加用户组'), ('edit_usergroup', '编辑用户组'), ('del_usergroup', '删除用户组')), 'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
    ]
