# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180304_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
    ]
