# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180304_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(default=None, to='accounts.UserGroup', verbose_name='用户组'),
        ),
    ]
