# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-06 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180304_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'default_permissions': (), 'permissions': (('get_usergroup', '查看用户组'), ('add_usergroup', '添加用户组'), ('edit_usergroup', '编辑用户组'), ('del_usergroup', '删除用户组')), 'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
    ]
