# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='approved_user',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='idc',
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[(1, '在线'), (2, '已下线'), (3, '故障'), (4, '备用')], default=None, max_length=16, null=True, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '在线'), (2, '已下线'), (3, '故障'), (4, '备用')], max_length=16, verbose_name='资产状态'),
        ),
        migrations.DeleteModel(
            name='NewAssetApprovalZone',
        ),
    ]
