# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20170813_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '在线'), (4, '备用'), (3, '故障'), (2, '已下线')], default=1, null=True, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '在线'), (4, '备用'), (3, '故障'), (2, '已下线')], default=1, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '路由器'), (2, '交换机'), (3, '负载均衡'), (4, 'VPN设备')], default=1, verbose_name='网络设备类型'),
        ),
    ]
