# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlist',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='rolelist',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
    ]
