# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=64, unique=True, verbose_name='资产名')),
                ('manage_ipaddress', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('other_ipaddress', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='其他IP')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('virtual machine', '虚拟机'), ('other', 'Other')], default='server', max_length=32, verbose_name='资产类型')),
                ('macaddress', models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商')),
                ('port_num', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='端口个数')),
                ('os_type', models.CharField(choices=[('centos', 'Centos'), ('macos', 'MacOs'), ('ubuntu', 'Ubuntu'), ('windows', 'Windows'), ('other', 'Other')], default='', max_length=32, verbose_name='系统类型')),
                ('os_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本')),
                ('status', models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('other', 'Other')], default='normal', max_length=32, verbose_name='状态')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产',
                'default_permissions': (),
                'verbose_name_plural': '资产',
                'permissions': (('get_asset', '查看资产'), ('add_asset', '添加资产'), ('edit_asset', '编辑资产'), ('del_asset', '删除资产')),
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='主机组')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产组',
                'default_permissions': (),
                'permissions': (('get_assetgroup', '查看资产组'), ('add_assetgroup', '添加资产组'), ('edit_assetgroup', '编辑资产组'), ('del_assetgroup', '删除资产组')),
                'verbose_name_plural': '资产组',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_num', models.IntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')),
                ('physical_num', models.IntegerField(blank=True, null=True, verbose_name='物理CPU个数')),
                ('vendor', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU厂商')),
                ('model_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU型号')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='每个CPU核数')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_size', models.IntegerField(default=0, verbose_name='磁盘大小')),
                ('disk_used', models.IntegerField(default=0, verbose_name='已使用磁盘大小')),
                ('disk_free', models.IntegerField(default=0, verbose_name='空闲磁盘大小')),
            ],
            options={
                'verbose_name': 'Disk',
                'verbose_name_plural': 'Disk',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机房名')),
                ('address', models.CharField(max_length=128, verbose_name='所在地址')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('network', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在网段')),
                ('operator', models.SmallIntegerField(choices=[(1, '电信'), (2, '联通'), (3, '移动'), (4, '铁通'), (5, '其他')], default=1, verbose_name='运营商')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('manage_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理人')),
            ],
            options={
                'verbose_name': '机房',
                'default_permissions': (),
                'permissions': (('get_idc', '查看机房'), ('add_idc', '添加机房'), ('edit_idc', '编辑机房'), ('del_idc', '删除机房')),
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_total', models.IntegerField(blank=True, null=True, verbose_name='内存总数')),
                ('mem_free', models.IntegerField(blank=True, null=True, verbose_name='内存空闲数')),
                ('mem_buffers', models.IntegerField(blank=True, null=True, verbose_name='buffers内存数')),
                ('mem_cached', models.IntegerField(blank=True, null=True, verbose_name='cached内存数')),
                ('mem_available', models.IntegerField(blank=True, null=True, verbose_name='可用内存数')),
                ('mem_used', models.IntegerField(blank=True, null=True, verbose_name='已使用内存数')),
                ('swap_mem_total', models.IntegerField(blank=True, null=True, verbose_name='虚拟内存数')),
                ('swap_mem_free', models.IntegerField(blank=True, null=True, verbose_name='虚拟内存空闲数')),
                ('swap_mem_used', models.IntegerField(blank=True, null=True, verbose_name='已使用虚拟内存数')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memory',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ManyToManyField(related_name='asset_group', to='assets.AssetGroup', verbose_name='资产组'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Cpu', verbose_name='Cpu信息'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Disk', verbose_name='磁盘信息'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_idc', to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Memory', verbose_name='内存信息'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('macaddress', 'sn', 'asset_name')]),
        ),
    ]
