# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-09 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=64, unique=True, verbose_name='资产名')),
                ('manage_ipaddress', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('other_ipaddress', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='其他IP')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('virtual machine', '虚拟机'), ('other', 'Other')], default='server', max_length=32, verbose_name='资产类型')),
                ('macaddress', models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商')),
                ('port', models.SmallIntegerField(blank=True, default=22, null=True, verbose_name='端口')),
                ('os_type', models.CharField(choices=[('centos', 'Centos'), ('macos', 'MacOs'), ('ubuntu', 'Ubuntu'), ('windows', 'Windows'), ('other', 'Other')], default='', max_length=32, verbose_name='系统类型')),
                ('os_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本')),
                ('mem_total', models.IntegerField(blank=True, null=True, verbose_name='内存总数')),
                ('mem_free', models.IntegerField(blank=True, null=True, verbose_name='内存空闲数')),
                ('mem_buffers', models.IntegerField(blank=True, null=True, verbose_name='buffers内存数')),
                ('mem_cached', models.IntegerField(blank=True, null=True, verbose_name='cached内存数')),
                ('mem_available', models.IntegerField(blank=True, null=True, verbose_name='可用内存数')),
                ('mem_used', models.IntegerField(blank=True, null=True, verbose_name='已使用内存数')),
                ('swap_mem_total', models.IntegerField(blank=True, null=True, verbose_name='虚拟内存数')),
                ('swap_mem_free', models.IntegerField(blank=True, null=True, verbose_name='虚拟内存空闲数')),
                ('swap_mem_used', models.IntegerField(blank=True, null=True, verbose_name='已使用虚拟内存数')),
                ('logical_num', models.IntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')),
                ('physical_num', models.IntegerField(blank=True, null=True, verbose_name='物理CPU个数')),
                ('vendor', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU厂商')),
                ('model_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU型号')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='每个CPU核数')),
                ('disk_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='磁盘大小')),
                ('disk_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='已使用磁盘大小')),
                ('disk_free', models.IntegerField(blank=True, default=0, null=True, verbose_name='空闲磁盘大小')),
                ('status', models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('other', 'Other')], default='normal', max_length=32, verbose_name='状态')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'permissions': (('view_asset_list', '访问资产列表'), ('view_asset', '查看资产'), ('add_asset', '添加资产'), ('change_asset', '修改资产'), ('delete_asset', '删除资产')),
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='主机组')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '资产组',
                'verbose_name_plural': '资产组',
                'permissions': (('view_assetgroup_list', '访问资产组列表'), ('view_assetgroup', '查看资产组'), ('add_assetgroup', '添加资产组'), ('change_assetgroup', '修改资产组'), ('delete_assetgroup', '删除资产组')),
            },
        ),
        migrations.CreateModel(
            name='AssetOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(default=(('add', '添加'), ('update', '更新'), ('delete', '删除'), ('other', 'Other')), max_length=32, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('assets', models.ManyToManyField(blank=True, related_name='assets_log', to='assets.Asset', verbose_name='资产对象')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '资产操作日志',
                'verbose_name_plural': '资产操作日志',
                'permissions': (('view_assetoperationlog_list', '访问资产行为日志列表'), ('view_assetoperationlog', '查看资产行为日志'), ('add_assetoperationlog', '添加资产行为日志'), ('change_assetoperationlog', '修改资产行为日志'), ('delete_assetoperationlog', '删除资产行为日志')),
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机房名')),
                ('address', models.CharField(max_length=128, verbose_name='所在地址')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('network', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在网段')),
                ('operator', models.SmallIntegerField(choices=[(1, '电信'), (2, '联通'), (3, '移动'), (4, '铁通'), (5, '其他')], default=1, verbose_name='运营商')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('manage_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理人')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'permissions': (('view_idc_list', '访问机房列表'), ('view_idc', '查看机房'), ('add_idc', '添加机房'), ('change_idc', '修改机房'), ('delete_idc', '删除机房')),
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'permissions': (('view_systemuser_list', '访问系统用户列表'), ('view_systemuser', '查看系统用户'), ('add_systemuser', '添加系统用户'), ('change_systemuser', '修改系统用户'), ('del_systemuser', '删除系统用户')),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ManyToManyField(related_name='asset_group', to='assets.AssetGroup', verbose_name='资产组'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_idc', to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='system_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='系统用户'),
        ),
    ]
