# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('manage_ipaddress', models.GenericIPAddressField(verbose_name='Manage ipaddress')),
                ('other_ipaddress', models.GenericIPAddressField(verbose_name='Other ipaddress')),
                ('macaddress', models.CharField(blank=True, max_length=64, null=True, verbose_name='Macaddress')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Serial number')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='Manufactory')),
                ('asset_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='Asset model')),
                ('host_type', models.CharField(choices=[('server', 'Server'), ('virtual machine', 'Virtual machine'), ('other', 'Other')], default='server', max_length=32, verbose_name='Host type')),
                ('os_type', models.CharField(choices=[('centos', 'Centos'), ('ubuntu', 'Ubuntu'), ('macOS', 'MacOS'), ('windows', 'Windows'), ('other', 'Other')], default='centos', max_length=32, verbose_name='Os type')),
                ('os_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='Os version')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='Cpu model')),
                ('cpu_num', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Cpu num')),
                ('cpu_cores', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Cpu cores')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='Memory')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disk')),
                ('status', models.CharField(blank=True, choices=[('normal', '正常'), ('measure', '故障'), ('scrap', '废弃'), ('other', 'Other')], max_length=32, null=True, verbose_name='Status')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update time')),
            ],
            options={
                'verbose_name_plural': 'Host',
                'verbose_name': 'Host',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Group name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update time')),
            ],
            options={
                'verbose_name_plural': 'HostGroup',
                'verbose_name': 'HostGroup',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Idc name')),
                ('address', models.CharField(max_length=128, verbose_name='Idc address')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('network', models.CharField(blank=True, max_length=32, null=True, verbose_name='Network')),
                ('operator', models.SmallIntegerField(choices=[(1, '电信'), (2, '联通'), (3, '移动'), (4, '铁通'), (5, '其他')], verbose_name='Operator')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update time')),
                ('manage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manage user')),
            ],
            options={
                'verbose_name_plural': 'IDC',
                'verbose_name': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=64, unique=True, verbose_name='Device name')),
                ('manage_ipaddress', models.GenericIPAddressField(verbose_name='Manage ipaddress')),
                ('other_ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='Other ipaddress')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='Cpu model')),
                ('port_num', models.SmallIntegerField(blank=True, null=True, verbose_name='Port num')),
                ('device_type', models.CharField(choices=[('route', 'Route'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('other', 'Other')], default='route', max_length=32, verbose_name='Device_type')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='Manufactory')),
                ('device_detail', models.TextField(blank=True, null=True, verbose_name='Device detail')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update time')),
                ('manage_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manage user')),
            ],
            options={
                'verbose_name_plural': 'NetworkDevice',
                'verbose_name': 'NetworkDevice',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.HostGroup', verbose_name='HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='Idc'),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manage user'),
        ),
    ]
