# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
        migrations.RemoveField(
            model_name='host',
            name='asset_model',
        ),
        migrations.AddField(
            model_name='host',
            name='host_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主机型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_cores',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='物理CPU个数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='CPU个数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(choices=[('server', '服务器'), ('virtual machine', '虚拟机'), ('other', 'Other')], default='server', max_length=32, verbose_name='主机类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.HostGroup', verbose_name='主机组'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AlterField(
            model_name='host',
            name='macaddress',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manage_ipaddress',
            field=models.GenericIPAddressField(verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manufactory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('centos', 'Centos'), ('ubuntu', 'Ubuntu'), ('macOS', 'MacOS'), ('windows', 'Windows'), ('other', 'Other')], default='centos', max_length=32, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='other_ipaddress',
            field=models.GenericIPAddressField(verbose_name='其他IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', '正常'), ('measure', '故障'), ('scrap', '废弃'), ('other', 'Other')], max_length=32, null=True, verbose_name='主机状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='主机组'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=128, verbose_name='所在地址'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='manage_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, verbose_name='机房名'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='network',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所在网段'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='operator',
            field=models.SmallIntegerField(choices=[(1, '电信'), (2, '联通'), (3, '移动'), (4, '铁通'), (5, '其他')], verbose_name='运营商'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_detail',
            field=models.TextField(blank=True, null=True, verbose_name='设备配置详情'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('route', '路由器'), ('switch', '交换机'), ('firewall', '防火墙'), ('other', 'Other')], default='route', max_length=32, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manage_ipaddress',
            field=models.GenericIPAddressField(verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manufactory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='other_ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='其他IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='port_num',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='接口个数'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
