# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Cpu', verbose_name='Cpu信息'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Disk', verbose_name='磁盘信息'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Memory', verbose_name='内存信息'),
        ),
    ]
