# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180323_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='memory',
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='每个CPU核数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_free',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='空闲磁盘大小'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='磁盘大小'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已使用磁盘大小'),
        ),
        migrations.AddField(
            model_name='asset',
            name='logical_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='逻辑CPU个数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_available',
            field=models.IntegerField(blank=True, null=True, verbose_name='可用内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_buffers',
            field=models.IntegerField(blank=True, null=True, verbose_name='buffers内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_cached',
            field=models.IntegerField(blank=True, null=True, verbose_name='cached内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存空闲数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存总数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mem_used',
            field=models.IntegerField(blank=True, null=True, verbose_name='已使用内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU型号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='physical_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='物理CPU个数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='swap_mem_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='虚拟内存空闲数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='swap_mem_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='虚拟内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='swap_mem_used',
            field=models.IntegerField(blank=True, null=True, verbose_name='已使用虚拟内存数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU厂商'),
        ),
        migrations.DeleteModel(
            name='Cpu',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
