# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180302_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='other_ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='其他IP'),
        ),
    ]
