# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180302_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('scrap', '废弃'), ('other', 'Other')], default='normal', max_length=32, verbose_name='主机状态'),
        ),
    ]
