# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180302_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_cores',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='逻辑CPU个数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='物理CPU个数'),
        ),
    ]
