# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180326_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'default_permissions': (), 'permissions': (('get_asset', '查看资产'), ('add_asset', '添加资产'), ('edit_asset', '编辑资产'), ('del_asset', '删除资产')), 'verbose_name': '资产', 'verbose_name_plural': '资产'},
        ),
        migrations.AlterModelOptions(
            name='assetgroup',
            options={'default_permissions': (), 'permissions': (('get_assetgroup', '查看资产组'), ('add_assetgroup', '添加资产组'), ('edit_assetgroup', '编辑资产组'), ('del_assetgroup', '删除资产组')), 'verbose_name': '资产组', 'verbose_name_plural': '资产组'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'default_permissions': (), 'permissions': (('get_idc', '查看机房'), ('add_idc', '添加机房'), ('edit_idc', '编辑机房'), ('del_idc', '删除机房')), 'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
    ]
