# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180326_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '资产', 'verbose_name_plural': '资产'},
        ),
        migrations.AlterModelOptions(
            name='assetgroup',
            options={'verbose_name': '资产组', 'verbose_name_plural': '资产组'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
    ]
