# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180304_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.ManyToManyField(blank=True, null=True, to='assets.HostGroup', verbose_name='主机组'),
        ),
    ]
