# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180304_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostgroup',
            field=models.ManyToManyField(blank=True, to='assets.HostGroup', verbose_name='主机组'),
        ),
    ]
