# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180304_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manage_ipaddress',
            field=models.GenericIPAddressField(unique=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='other_ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='其他IP'),
        ),
    ]
