# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180305_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主机型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(choices=[('server', '服务器'), ('virtual machine', '虚拟机'), ('other', 'Other')], default='server', max_length=16, verbose_name='主机类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=32, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='macaddress',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('centos', 'Centos'), ('ubuntu', 'Ubuntu'), ('macOS', 'MacOS'), ('windows', 'Windows'), ('other', 'Other')], default='centos', max_length=16, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('scrap', '废弃'), ('other', 'Other')], default='normal', max_length=16, verbose_name='主机状态'),
        ),
    ]
