# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20180305_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'default_permissions': (), 'permissions': (('get_host', '查看主机'), ('add_host', '添加主机'), ('edit_host', '编辑主机'), ('del_host', '删除主机')), 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'default_permissions': (), 'permissions': (('get_hostgroup', '查看主机组'), ('add_hostgroup', '添加主机组'), ('edit_hostgroup', '编辑主机组'), ('del_hostgroup', '删除主机组')), 'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'default_permissions': (), 'permissions': (('get_idc', '查看机房'), ('add_idc', '添加机房'), ('edit_idc', '编辑机房'), ('del_idc', '删除机房')), 'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'default_permissions': (), 'permissions': (('get_network_device', '查看网络设备'), ('add_network_device', '添加网络设备'), ('edit_network_device', '编辑网络设备'), ('del_network_device', '删除网络设备')), 'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
    ]
