# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20180305_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='operator',
            field=models.SmallIntegerField(choices=[(1, '电信'), (2, '联通'), (3, '移动'), (4, '铁通'), (5, '其他')], default=1, verbose_name='运营商'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话'),
        ),
    ]
