# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20180307_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='macaddress',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MAC地址'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SN号'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('other', 'Other')], default='normal', max_length=32, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('measure', '故障'), ('other', 'Other')], default='normal', max_length=32, verbose_name='主机状态'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('macaddress', 'sn')]),
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='cpu_model',
        ),
        migrations.AlterUniqueTogether(
            name='networkdevice',
            unique_together=set([('macaddress', 'sn')]),
        ),
    ]
