# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20180307_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='macaddress',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SN号'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('hostname', 'macaddress', 'sn')]),
        ),
        migrations.AlterUniqueTogether(
            name='networkdevice',
            unique_together=set([('device_name', 'macaddress', 'sn')]),
        ),
    ]
