# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20180326_2209'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetactionpermission',
            name='asset_groups',
        ),
        migrations.RemoveField(
            model_name='assetactionpermission',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='assetactionpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user_groups',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.RemoveField(
            model_name='urlviewpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='accounts.UserGroup', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='urlviewpermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='urlviewpermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AssetActionPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
