# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0006_auto_20180326_2209'),
        ('accounts', '0011_auto_20180326_2209'),
        ('permission', '0002_auto_20180327_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetActionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='权限名')),
                ('can_view', models.BooleanField(default=False, verbose_name='是否可查看')),
                ('can_add', models.BooleanField(default=False, verbose_name='是否可添加')),
                ('can_change', models.BooleanField(default=False, verbose_name='是否可更新')),
                ('can_delete', models.BooleanField(default=False, verbose_name='是否可删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('asset_groups', models.ManyToManyField(blank=True, related_name='asset_permission', to='assets.AssetGroup', verbose_name='资产组')),
                ('assets', models.ManyToManyField(blank=True, related_name='asset_permission', to='assets.Asset', verbose_name='资产')),
                ('user_groups', models.ManyToManyField(blank=True, related_name='user_asset_permission', to='accounts.UserGroup', verbose_name='用户组')),
                ('users', models.ManyToManyField(blank=True, related_name='user_asset_permission', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资产操作权限',
                'verbose_name_plural': '资产操作权限',
            },
        ),
    ]
